#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
ufw enable
echo "Hello World!" > /etc/nginx/html/index.nginx-debian.html
printf %s "server {
    location /redirect_me {
        return 301 Moved Permanently;
    }
}" >> /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
