#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'

echo "Hello World!" > /etc/nginx/html/index.nginx-debian.html
printf %s "server {
    listen	 80 default_server;
    listen	 [::]:80 default_server;
    root	 /var/www/html;
    index 	index.html index.htm index.nginx-debian.html;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }
}" > /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
