#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root         /var/www/html;
    index       index.html index.htm index.nginx-debian.html;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }
    error_page 404 /custom_404.html;
    location /404 {
        root /var/www/html/custom_404.html;
	internal;
    }
}" > /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
