#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+ Enables management via the init script.
#+ Distributes requests using a round-robin algorithm

apt-get update
apt-get install -y haproxy

echo "ENABLE=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 65087-web-01 54.209.135.247:80 check
   server 65087-web-02 3.90.85.92:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
