#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

file="/etc/passwd"

while IFS= read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < "$file"
